modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues"

[[mods]]
modId="vehicle"
version="0.45.2-1.20.1"
displayName="MrCrayfish's Vehicle Mod"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=vehicle"
displayURL="https://mrcrayfish.com/mods?id=vehicle"
logoFile="vehicle_mod.png"
credits="Phylogeny https://github.com/Phylogeny"
authors="MrCrayfish"
description="A mod that adds vehicles into Minecraft!"

[[dependencies.vehicle]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vehicle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
